### ISSUE TITLE
QA - Iterator powered Filesystem class

### ISSUE THREAD

**Issue by redaxmedia** [redaxmedia/redaxscript#150]
We need to switch to <code>RecursiveDirectoryIterator</code> and <code>RecursiveIteratorIterator</code> but without breaking the current code.

- [x] Switch the whole class to the easy to use Iterators
- [x] Keep getArray() as it is
- [x] Introduce new getRecursiveArray
- [x] Refactor Cache (store method) to the new class

Hint: Once this was refactored, we have to use the new Directory class in documentation-sync:
https://github.com/redaxmedia/redaxscript-documentation-sync/blob/master/sync.php#L46-L47

**Comment by redaxmedia** [comment]
Done

**Comment by redaxmedia** [comment]
Done
