### ISSUE TITLE
Epic - OOP refactoring - install.php

### ISSUE THREAD

**Issue by redaxmedia** [redaxmedia/redaxscript#273]
Refactor install.php...

- [x] Replace the fake functions like center() and head() with pure template code
- [x] Handle routing via router.php
- [x] Errors via Messenger
  - [ ] No permission to config.php or sqlite file
  - [x] Wrong PHP version
  - [x] No PDO driver (sqlite, mysql, postresql) installed
  - [x] No Session (session_status)
- [x] Warnings via Messenger
  - [x] Not running under Linux
  - [x] No .htaccess file
  - [x] No mod_deflate
  - [x] No mod_rewrite
- [x] The Cli should return an error code on failure

Classes: 

- [x] Console/Command/Install (related issue #416)
- [ ] Controller/Install
- [x] View/InstallStatus (provides errors and warnings via Messenger)
- [x] View/InstallForm

WIP:

http://pastebin.com/5BLAECUD

**Comment by redaxmedia** [comment]
1. create a dataprovider with the registry array
1. are using the Registry class via depedency injection in the constructor of the installStatus
1 write the methods to validate the stuff
1. write the methods to show message
1. add more dataprovider
1. set the registry keys in the "real world" what means startup.php
1. watch the installStatus output on the install.php or where you did a output

**Comment by redaxmedia** [comment]
TDD @ Controller\Install

1. create a Install controller using the ControllerAbstract
1. override the constructor to provide a Config instance
1. write a Controller\InstallTest with a basic setup and dataprovider
1. **trick to success**: ignore the fact that we install something, let the <code>_install</code> method return true to fake a success - we take care about it later
1. write the methods to validate only $_POST from the form
1. write the methods to show message
1. add more dataprovider for the different conditions
1. **trick to success**: once everything is working, we take care that the <code>_install</code> method actually installs something and returns a boolean according to fail or success
1. add more dataprovider to simulate a install failure or success
1. finally, test the install controller in the real world - it should actually work

Related to 2. point
<pre>
/**
 * instance of the config class
 *
 * @var object
 */
protected $_config;

public function __construct(Registry $registry, Language $language, Request $request, Config $config)
{
	$this->_registry = $registry;
	$this->_language = $language;
	$this->_request = $request;

       //maybe use "parent" instead of the code above: parent::__construct($registry, $language, $request);
	$this->_request = $config;
}
</pre>
