### ISSUE TITLE
Template variations

### ISSUE THREAD

**Issue by redaxmedia** [redaxmedia/redaxscript#341]
The idea is to automatically generate a bunch of variations from the default template:
1. Topic related header image
2. Custom set of colors
3. Custom Google fonts

![variation](https://cloud.githubusercontent.com/assets/1835397/12494657/d4c0f6e0-c08b-11e5-9c4f-66db223e0827.png)

![variation](https://snag.gy/MINfeR.jpg)

Collection of blog topics:
1. Default (neutral)
2. Band / Musician
3. Artist / Designer
4. Travel / Holiday
5. Industry / Economy
6. Business / Office
7. Education / School
8. Photographer
9. Nerd / Developer
10. Technology
11. Food / Cooking
12. Gaming
13. Fashion / Lifestyle
14. Automobile
15. Culture
16. Nature / Animals
17. Phylosophy / Writer / Novel
18. Finance / Stock market
19. Health / Fitness
20. Product / Review
21. Diary / Newspaper
22. Architecture

Todo:
- [ ] Select the most interesting topics
- [ ] Find stock photos to each of the topic / Shot your own photos
- [ ] Find color and typography combinations (Photoshop)

Resources / Tools:

http://makerbook.net/photography
http://www.entrepreneur.com/article/238646
https://bootstrapbay.com/blog/free-stock-photos
https://www.google.com/fonts
http://sachagreif.com/more-google-webfonts-that-dont-suck
https://color.adobe.com
http://lokeshdhakar.com/projects/color-thief
http://somadesign.ca/projects/fontfriend
https://github.com/danielgavrilov/WebFontPicker

**TeaserImage bookmarklet:**

<pre>
$('.rs-component-teaser').css({
  'background-image': 'url(' + prompt('teaser-image') + ')',
  'background-position': 'center'
});
</pre>

<pre>javascript:(function()%7B%24('.rs-component-teaser').css(%7B'background-image'%3A%20'url('%20%2B%20prompt('teaser-image')%20%2B%20')'%2C'background-position'%3A%20'center'%7D)%7D)()</pre>

**RandomTeaserImage bookmarklet:**

<pre>
$('.rs-component-teaser').css({
  'background': 'url(https://unsplash.it/' + window.innerWidth + '/' +  window.innerWidth / 3 + '/?random&=' + Date.now(),
  'background-position': 'center'
});
</pre>

<pre>
javascript:(function()%7B%24('.rs-component-teaser').css(%7B'background'%3A%20'url(https%3A%2F%2Funsplash.it%2F'%20%2B%20window.innerWidth%20%2B%20'%2F'%20%2B%20%20window.innerWidth%20%2F%203%20%2B%20'%2F%3Frandom%26%3D'%20%2B%20Date.now()%2C'background-position'%3A%20'center'%7D)%7D)()
</pre>

**WebFontPicker bookmarklet:**

<pre>.rs-title-extra, .rs-title-website, .rs-title-teaser, .rs-list-header li</pre>

**ColorPicker bookmarklet:**

<pre>
function hex (x) {
    if (x) {
        return ("0" + parseInt(x).toString(16)).slice(-2);
    }
}

function rgbToHex (rgb) {
    if (rgb && rgb.indexOf('rgb') > -1) {
        rgb = rgb.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/);
        if (rgb !== null) {
          return "#" + hex(rgb[1]) + hex(rgb[2]) + hex(rgb[3]);        
        }
    }
    if (rgb && rgb.indexOf('#') > -1) {
        return rgb;
    }
}

function hexToRgba (hex, alpha) {
    hex = hex.replace('#', '');
    var bigint = parseInt(hex, 16),
        r = (bigint >> 16) & 255,
        g = (bigint >> 8) & 255,
        b = bigint & 255,
        a = alpha > 0 ? alpha : 1;

    return r + "," + g + "," + b + "," + a;
}

var box = $('<div>'),
    inputLabel = $('<label>'),
    inputText = $('<input>'),
    inputColor = $('<input type="color">'),
    dataArray = [{
        selector: '.rs-header, .rs-sidebar, .rs-footer, .rs-title-teaser',
        property: 'background-color',
        description: 'hintergrund des header, teaser sidebar und footer'
    }, {
        selector: '.rs-title-header, .rs-text-header, .rs-sidebar, .rs-footer, .rs-title-teaser',
        property: 'color',
        description: 'textfarbe des header, teaser sidebar und footer'
    }, {
        selector: '.rs-list-menu a, .rs-list-menu span',
        property: 'background',
        description: 'hintergrund der navi'
    }, {
        selector: '.rs-list-menu',
        property: 'color',
        description: 'textfarbe der navi'
    }, {
        selector: '.rs-title-teaser',
        property: 'border-left-color',
        description: 'akzentfarbe im teaser'
    }, {
        selector: '.rs-content, .rs-content *',
        property: 'color',
        description: 'textfarbe des inhalt'
    }],
    i;
inputLabel
    .css({
        display: 'block',
        color: '#666',
        clear: 'both',
        fontSize: '0.875em',
        fontWeight: 'bold',
        margin: '0 2%'
    });
inputText
    .css({
        border: '1px solid #ddd',
        color: '#666',
        padding: '0.25em',
        float: 'left',
        margin: '2%',
        width: '70%'
    });
inputColor
    .css({
        background: 'transparent',
        border: 'none',
        float: 'right',
        height: '1.875em',
        margin: '2%',
        width: '20%'
    });

inputText.add(inputColor)
    .on('change', function() {
        var that = $(this),
            type = that.attr('type'),
            color = that.val(),
            selector = that.attr('data-selector'),
            property = that.attr('data-property');

        if (type === 'color') {
            that
                .prev()
                .val(color);
        } else {
            that
                .next()
                .val(color);
        }
        $(selector).css(property, color);
        if (property === 'background-color' && selector.indexOf('.rs-title-teaser') > -1) {
            $('.rs-title-teaser').css({
                'background': 'rgba(' + hexToRgba(color, 0.8) + ')'
            });
        }
    });

for (i in dataArray) {
    var thatColor = rgbToHex($(dataArray[i].selector).first().css(dataArray[i].property)),
        thatLabel = inputLabel.clone(true).text(dataArray[i].description),
        thatText = inputText.clone(true).val(thatColor),
        thatColor = inputColor.clone(true).val(thatColor);

    inputText.add(thatColor).attr({
        'data-selector': dataArray[i].selector,
        'data-property': dataArray[i].property
    });

    box
        .append(thatLabel)
        .append(thatText)
        .append(thatColor);
}

box
    .css({
        background: 'rgba(255, 255, 255, 0.8)',
        boxShadow: '0 0 0.5em rgba(0, 0, 0, 0.4)',
        bottom: 0,
        fontSize: '0.875rem',
        position: 'fixed',
        padding: '0.5em',
        right: 0,
        zIndex: 10000
    })
    .appendTo('body');</pre>

<pre>
javascript:(function()%7Bfunction%20hex%20(x)%20%7Bif%20(x)%20%7Breturn%20(%220%22%20%2B%20parseInt(x).toString(16)).slice(-2)%3B%7D%7Dfunction%20rgbToHex%20(rgb)%20%7Bif%20(rgb%20%26%26%20rgb.indexOf('rgb')%20%3E%20-1)%20%7Brgb%20%3D%20rgb.match(%2F%5Ergb%5C((%5Cd%2B)%2C%5Cs*(%5Cd%2B)%2C%5Cs*(%5Cd%2B)%5C)%24%2F)%3Bif%20(rgb%20!%3D%3D%20null)%20%7Breturn%20%22%23%22%20%2B%20hex(rgb%5B1%5D)%20%2B%20hex(rgb%5B2%5D)%20%2B%20hex(rgb%5B3%5D)%3B%7D%7Dif%20(rgb%20%26%26%20rgb.indexOf('%23')%20%3E%20-1)%20%7Breturn%20rgb%3B%7D%7Dfunction%20hexToRgba%20(hex%2C%20alpha)%20%7Bhex%20%3D%20hex.replace('%23'%2C%20'')%3Bvar%20bigint%20%3D%20parseInt(hex%2C%2016)%2Cr%20%3D%20(bigint%20%3E%3E%2016)%20%26%20255%2Cg%20%3D%20(bigint%20%3E%3E%208)%20%26%20255%2Cb%20%3D%20bigint%20%26%20255%2Ca%20%3D%20alpha%20%3E%200%20%3F%20alpha%20%3A%201%3Breturn%20r%20%2B%20%22%2C%22%20%2B%20g%20%2B%20%22%2C%22%20%2B%20b%20%2B%20%22%2C%22%20%2B%20a%3B%7Dvar%20box%20%3D%20%24('%3Cdiv%3E')%2CinputLabel%20%3D%20%24('%3Clabel%3E')%2CinputText%20%3D%20%24('%3Cinput%3E')%2CinputColor%20%3D%20%24('%3Cinput%20type%3D%22color%22%3E')%2CdataArray%20%3D%20%5B%7Bselector%3A%20'.rs-header%2C%20.rs-sidebar%2C%20.rs-footer%2C%20.rs-title-teaser'%2Cproperty%3A%20'background-color'%2Cdescription%3A%20'hintergrund%20des%20header%2C%20teaser%20sidebar%20und%20footer'%7D%2C%20%7Bselector%3A%20'.rs-title-header%2C%20.rs-text-header%2C%20.rs-sidebar%2C%20.rs-footer%2C%20.rs-title-teaser'%2Cproperty%3A%20'color'%2Cdescription%3A%20'textfarbe%20des%20header%2C%20teaser%20sidebar%20und%20footer'%7D%2C%20%7Bselector%3A%20'.rs-list-menu%20a%2C%20.rs-list-menu%20span'%2Cproperty%3A%20'background'%2Cdescription%3A%20'hintergrund%20der%20navi'%7D%2C%20%7Bselector%3A%20'.rs-list-menu'%2Cproperty%3A%20'color'%2Cdescription%3A%20'textfarbe%20der%20navi'%7D%2C%20%7Bselector%3A%20'.rs-title-teaser'%2Cproperty%3A%20'border-left-color'%2Cdescription%3A%20'akzentfarbe%20im%20teaser'%7D%2C%20%7Bselector%3A%20'.rs-content%2C%20.rs-content%20*'%2Cproperty%3A%20'color'%2Cdescription%3A%20'textfarbe%20des%20inhalt'%7D%5D%2Ci%3BinputLabel.css(%7Bdisplay%3A%20'block'%2Ccolor%3A%20'%23666'%2Cclear%3A%20'both'%2CfontSize%3A%20'0.875em'%2CfontWeight%3A%20'bold'%2Cmargin%3A%20'0%202%25'%7D)%3BinputText.css(%7Bborder%3A%20'1px%20solid%20%23ddd'%2Ccolor%3A%20'%23666'%2Cpadding%3A%20'0.25em'%2Cfloat%3A%20'left'%2Cmargin%3A%20'2%25'%2Cwidth%3A%20'70%25'%7D)%3BinputColor.css(%7Bbackground%3A%20'transparent'%2Cborder%3A%20'none'%2Cfloat%3A%20'right'%2Cheight%3A%20'1.875em'%2Cmargin%3A%20'2%25'%2Cwidth%3A%20'20%25'%7D)%3BinputText.add(inputColor).on('change'%2C%20function()%20%7Bvar%20that%20%3D%20%24(this)%2Ctype%20%3D%20that.attr('type')%2Ccolor%20%3D%20that.val()%2Cselector%20%3D%20that.attr('data-selector')%2Cproperty%20%3D%20that.attr('data-property')%3Bif%20(type%20%3D%3D%3D%20'color')%20%7Bthat.prev().val(color)%3B%7D%20else%20%7Bthat.next().val(color)%3B%7D%24(selector).css(property%2C%20color)%3Bif%20(property%20%3D%3D%3D%20'background-color'%20%26%26%20selector.indexOf('.rs-title-teaser')%20%3E%20-1)%20%7B%24('.rs-title-teaser').css(%7B'background'%3A%20'rgba('%20%2B%20hexToRgba(color%2C%200.8)%20%2B%20')'%7D)%3B%7D%7D)%3Bfor%20(i%20in%20dataArray)%20%7Bvar%20thatColor%20%3D%20rgbToHex(%24(dataArray%5Bi%5D.selector).first().css(dataArray%5Bi%5D.property))%2CthatLabel%20%3D%20inputLabel.clone(true).text(dataArray%5Bi%5D.description)%2CthatText%20%3D%20inputText.clone(true).val(thatColor)%2CthatColor%20%3D%20inputColor.clone(true).val(thatColor)%3BinputText.add(thatColor).attr(%7B'data-selector'%3A%20dataArray%5Bi%5D.selector%2C'data-property'%3A%20dataArray%5Bi%5D.property%7D)%3Bbox.append(thatLabel).append(thatText).append(thatColor)%3B%7Dbox.css(%7Bbackground%3A%20'rgba(255%2C%20255%2C%20255%2C%200.8)'%2CboxShadow%3A%20'0%200%200.5em%20rgba(0%2C%200%2C%200%2C%200.4)'%2Cbottom%3A%200%2CfontSize%3A%20'0.875rem'%2Cposition%3A%20'fixed'%2Cpadding%3A%20'0.5em'%2Cright%3A%200%2CzIndex%3A%2010000%7D).appendTo('body')%7D)()</pre>

**Comment by redaxmedia** [comment]
Closed because the planned Cameleon template is enough for the moment.
