### ISSUE TITLE
Epic - Updates for modules

### ISSUE THREAD

**Issue by redaxmedia** [redaxmedia/redaxscript#343]
Refactoring
=========
- [x] Each module with CSS needs an visual update
- [x] Use _variable.css and _icon.css from the default template
- [x] Follow the NCSS principles
- [x] Create icon fonts from SVG files in <code>/dist/fonts</code>
- [x] Replace the global loader() with the new Head bundle*¹
- [x] Fix the static calls like Registry::get() etc. inside all modules*²
- [x] Use CSSNano to create .css.min packages
- [x] Use UglifyJS to create .js.min packages
- [x] Switch to <code>!is_dir() && !mkdir()</code> blocks instead of <code>is_dir()</code>
- [x] Improve the docs
  - [x] There is nothing said about config.php or init.js
  - [x] The p tags need more spacing to the code tags

Todos and bugs
=============
 - [x] HTML Validator seems to be broken, does not show errors
 - [x] Share This: fires 7 requests to the API instead of a single
 - [x] Tinymce:
  - <del>Pass the current google font to the iframe</del>
  - Form Validation silently failes: empty textarea causes error but div container is not errored
  - [Upload callback](https://www.tinymce.com/docs/configure/file-image-upload/#file_browser_callback) is missing, so there is not Icon for local directory browsing
 - [x] PageCache: There is a bug while switching the template or language via URL because the Query is not added to the caching logic. We need something like: $fullRoute = $registry->get('fullRoute') . $request->getQuery('t') . $request->getQuery('l');
 - [x] PageCache: Solve issue with page caching vs. assets caching: page lifetime reduced to 1h

Overview
=======

<table>
    <thead>
        <tr>
            <th>Module</th>
            <th>Visual update</th>        
            <th>PostCSS with @import</th>
            <th>NCSS</th>
            <th>Icon Font</th>
            <th>PHP Head*¹</th>
            <th>PHP Static*²</th>
            <th>CSSNano</th>
            <th>UglifyJS</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Ace</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
            <td>-</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
         </tr><tr>
            <td>Analytics</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>true</td>
            <td>true</td>
            <td>-</td>
            <td>true</td>
         </tr><tr>
            <td>Archive</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>true</td>
            <td>-</td>
            <td>-</td>
         </tr><tr>
            <td>CallHome</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>true</td>
            <td>true</td>
            <td>-</td>
            <td>true</td>
         </tr><tr>
            <td>Contact</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>true</td>
            <td>-</td>
            <td>-</td>
         </tr><tr>
            <td>Demo</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>true</td>
            <td>-</td>
            <td>-</td>
         </tr><tr>
            <td>DirectoryLister</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
            <td>-</td>
         </tr><tr>
            <td>Disqus</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>true</td>
            <td>true</td>
            <td>-</td>
            <td>true</td>
         </tr><tr>
            <td>Experiments</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>true</td>
            <td>true</td>
            <td>-</td>
            <td>true</td>
         </tr><tr>
         </tr><tr>
            <td>FeedGenerator</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>true</td>
            <td>-</td>
            <td>-</td>
         </tr><tr>
            <td>FeedReader</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
            <td>-</td>
         </tr><tr>
            <td>Gallery</td>
            <td><strong>false</strong></td>
            <td><strong>false</strong></td>
            <td><strong>false</strong></td>
            <td><strong>false</strong></td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
         </tr><tr>
             <td>Maps</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
            <td>-</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
         </tr><tr>
         </tr><tr>
            <td>Preview</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
            <td>-</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
            <td>-</td>
         </tr><tr>
            <td>ShareThis</td>
            <td>-</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
            <td>-</td>
         </tr><tr>
            <td>Sitemap</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>true</td>
            <td>-</td>
            <td>-</td>
         </tr><tr>
         </tr><tr>
            <td>SitemapXml</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>true</td>
            <td>-</td>
            <td>-</td>
         </tr><tr>
         </tr><tr>
            <td>SyntaxHighlighter</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>true</td>
            <td>true</td>
            <td>-</td>
            <td>true</td>
         </tr><tr>
            <td>TestDummy</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>true</td>
            <td>-</td>
            <td>-</td>
         </tr><tr>
            <td>Tinymce</td>
            <td><strong>false</strong></td>
            <td>true</td>
            <td>true</td>
             <td>true</td>
            <td>true</td>
            <td>true</td>
            <td>true</td>
           <td>true</td>
         </tr><tr>
            <td>Validator</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>true</td>
            <td>-</td>
            <td>-</td>
         </tr><tr>
    </tbody>
</table>

**Comment by redaxmedia** [comment]
Done
