### ISSUE TITLE
Wiki updates for 3.0.0

### ISSUE THREAD

**Issue by redaxmedia** [redaxmedia/redaxscript#355]
- [ ] Module hooks were renamed -> update module events section
   - [ ] What parameter are passed to the hooks
- [ ] Update scripts and styles path to new assets/scripts and assets/styles
   - [ ] Describe how to define url() in path - for example <code> ../../../../templates/default/dist/fonts</code> instead of <code>../fonts</code> (needed for caching)
- [ ] New section - How to use assets / Guide to use PostCSS
- [x] <del>Update all kind of namespace changes (compare via APIGen docs)<del>
- [x] <del> Users sections - howto for registration, login and reminder</del>
- [x] <del>Groups section - admins vs. members vs. custom permissions</del>
- [x] <del>Reference</del>
   - [x] <del>Messenger</del>
   - [x] <del>Auth</del>
   - [x] <del>New Template namespace</del>
- [ ] Updates on base and global form (cancel, delete, save, create)
- [x] Template Tags changed to Tag::name
- [x] Unmask password changed to ctrl + alt + u
- [ ] Console Reference
    - [ ] Installation guide via console.php
- [ ] Config has new parse method
- [ ] Some options were renamed to optionArray and exclude to excludeArray
- [ ] Directory has new PUT method
- [ ] New Reader class to fetch JSON and XML and later convert
- [ ] Modules Notification - add example how to add notifications like self::addNotification();
- [ ] Assetic and Head bundle Reference
- [x] <del>Remove "grunt sync" task from Github guide</del>
- [x] Rename pseudo tag codequote to blockcode
- [x] Add Docker guide that shows how to use docker and docker-compose
- [ ] How is Cache working? How to disable Cache temporary and permanent?
- [x] Troubleshooting needs update for Blank page - extend it with XAMPP issue: https://community.bitnami.com/t/error-after-install-fatal-error-cannot-redeclare-class-config/25114/3
- [x] <del>Update Tag::articleRaw(); and Tag::extraRaw();</del>

Example for cache clear:

<pre>
//clear everything
cache clear
//clear styles folder
cache clear --directory=cache/styles
//clear bundle in styles folder
cache clear --directory=cache/styles --extension=css --bundle=templates/console/dist/styles/console.min.css
</pre>

**Comment by redaxmedia** [comment]
Done
