### ISSUE TITLE
QA - Fix warnings and reduce static code

### ISSUE THREAD

**Issue by redaxmedia** [redaxmedia/redaxscript#421]
- [x] Fix most warnings in the codebase
- [x] Remove static properties and methods - should only be used for DI
  - [x] Core
  - [x] Modules
  - [x] Refactor the Admin/View/Helper/Option to non static
- [x] Remove static calls like Registy::get() and Language::get()
- [x] Let PHPUnit fail on warnings

# Static

Just search for "static function" in the includes folder.

Before:
<pre>
Helper\Option::getLanguageArray()
</pre>

After:
<pre>
$helperOption = new Helper\Options(Language $language)
$helperOption->getLanguageArray()
</pre>

# Warning

> This is insane. You gain a 265% performance boost by avoiding code that produce warnings.
> http://idiallo.com/blog/fix-all-php-warnings

Set <code>error_reporting(E_WARNING);</code> inside <code>tests/phpunit/TestCaseAbstract.php</code> and fix all warnings!
- Work in a extra branch
- Keep the E_WARNING enabled for PHPUnit after refactoring

**Comment by redaxmedia** [comment]
Done
