### ISSUE TITLE
Support for MSSQL database

### ISSUE THREAD

**Issue by redaxmedia** [redaxmedia/redaxscript#502]
Here is a checklist to merge the experimental branch with the basic support:

- [x] Db class
- [x] Fix testing suite
- [x] Console commands
  - [x] Backup
  - [x] Restore
  - [x] Status
- [x] View/Systemstatus
- [x] Installation wizard
- [x] Update documentation
  - [x] Installation
  - [x] Configuration
- [x] CI on https://www.appveyor.com
- [x] Extend Docker container

**Comment by redaxmedia** [comment]
Done
