### ISSUE TITLE
Epic - Default template from scratch

### ISSUE THREAD

**Issue by joergsteinhauer** [redaxmedia/redaxscript#64]
Lets create a fresh and fancy default template, clean, flat, modern and even more responsive. Mobile first this time.

1. The old template will be renamed to "classic" and is still available
 - Please remove all deprecated 2.x.x templates, accept the scratch and classic template
 - Scratch templates needs another look
 - Update the scratch and classic template to 3.x.x structure
1. Restructure Base and Templates Styles and update the [Wiki](https://github.com/redaxmedia/redaxscript/wiki/Styles)
 - Put all <code>scripts</code> and <code>styles</code> folders into a parent <code>assets</code> folder
1. A concept for http://redaxscript.com should be screened for a better joy of use
 - Please get more information from Issue https://github.com/redaxmedia/redaxscript/issues/245

![rxs_inspire_02](https://cloud.githubusercontent.com/assets/1843754/6098403/b5f0b7c4-afdd-11e4-811a-069fdcb935f4.jpg)

Technical details:
- [x] Rename CSS-Classes by using new namspaces
- [x] Revise all CSS base styles: combine, move to template and use a new normalize styles
- [x] Develop a new flat logo style, e.g. rectangle-logo 
- [x] <del>For admin elements use REM instead of EM</del>
- [x] <del>Footer: try to remove lists and use more social media contacts, convertion formular etc.</del>
- [x] Main navigation: try to develop a navigation without dropdown

CMS website collection:

* https://ghost.org
* http://picocms.org
* http://modx.com
* http://anchorcms.com
* http://concrete5.org

**Comment by redaxmedia** [comment]
Visual review:

- [ ] Sign and the typo must be a unit

Technical review:

- [ ] Semantic structure: header - teaser - main (content / sidebar) - footer

**Comment by redaxmedia** [comment]
I reconsidered my decision, it is better to keep the old template as classic!

**Comment by redaxmedia** [comment]
I played with Firebug, because I think the Redaxscript template should be much more cleaner!

Before: http://i.share.pho.to/1cd60a47_o.png
After: http://i.share.pho.to/bd87c0dd_o.png

**Comment by redaxmedia** [comment]
Creative Link Effects: http://tympanus.net/Development/CreativeLinkEffects/

**Comment by redaxmedia** [comment]
Next steps:

- [] Move to a clean 3.0.0 branch that was build upon current master
- [] Remove donate and support Icons

**Comment by redaxmedia** [comment]
False usage of viewport units:

1. Don't give a container a fixed height
1. Don't use VH for padding (portrait is broken)
1. Whitespace after the footer on landscape
1. Bottom container and margin-top is not needed

![layout_issue_01](https://cloud.githubusercontent.com/assets/1835397/11320182/688ad700-9090-11e5-82d5-306a2e2c5f98.png)
![layout_issue_02](https://cloud.githubusercontent.com/assets/1835397/11320183/6a729012-9090-11e5-8334-3c33334af58c.png)
![layout_issue_03](https://cloud.githubusercontent.com/assets/1835397/11320184/6c08c0ea-9090-11e5-9bdb-bd2d3d92c06a.png)

**Comment by redaxmedia** [comment]
Done
